// @ts-nocheck

/**
 * Auto Generated by orval
 * Do not edit manually.
 * BaseApp Backend API
 * API para el sistema de BaseApp Backend
 */

export type FormsResultListParams = {
  /**
   * A search term.
   */
  search?: string;
};

export type FormsListParams = {
  /**
   * A search term.
   */
  search?: string;
};

export interface UserRegistration {
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username: string;
  /** @maxLength 254 */
  email?: string;
  password: string;
}

export interface User {
  readonly id: number;
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username: string;
  /** @maxLength 254 */
  email?: string;
}

/**
 * * `Muy importante` - Muy Importante
 * `Importante` - Importante
 * `Poco importante` - Poco Importante
 * `Nada importante` - Nada Importante
 */
export enum UnemploymentRateEnum {
  Muy_importante = "Muy importante",
  Importante = "Importante",
  Poco_importante = "Poco importante",
  Nada_importante = "Nada importante",
}
export interface TokenRefresh {
  readonly access: string;
  refresh: string;
}

export interface Result {
  pais: string;
  continente: string;
  score: number;
}

export interface PatchedUser {
  readonly id?: number;
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username?: string;
  /** @maxLength 254 */
  email?: string;
}

/**
 * * `Muy importante` - Muy Importante
 * `Importante` - Importante
 * `Poco importante` - Poco Importante
 * `Nada importante` - Nada Importante
 */
export enum LowInflationEnum {
  Muy_importante = "Muy importante",
  Importante = "Importante",
  Poco_importante = "Poco importante",
  Nada_importante = "Nada importante",
}
/**
 * * `Muy importante` - Muy Importante
 * `Importante` - Importante
 * `Poco importante` - Poco Importante
 * `Nada importante` - Nada Importante
 */
export enum LivingAreaEnum {
  Muy_importante = "Muy importante",
  Importante = "Importante",
  Poco_importante = "Poco importante",
  Nada_importante = "Nada importante",
}
/**
 * * `Muy importante` - Muy Importante
 * `Importante` - Importante
 * `Poco importante` - Poco Importante
 * `Nada importante` - Nada Importante
 */
export enum JobSecurityEnum {
  Muy_importante = "Muy importante",
  Importante = "Importante",
  Poco_importante = "Poco importante",
  Nada_importante = "Nada importante",
}
/**
 * * `Muy importante` - Muy Importante
 * `Importante` - Importante
 * `Poco importante` - Poco Importante
 * `Nada importante` - Nada Importante
 */
export enum HealthcareImportanceEnum {
  Muy_importante = "Muy importante",
  Importante = "Importante",
  Poco_importante = "Poco importante",
  Nada_importante = "Nada importante",
}
/**
 * * `Hombre` - Male
 * `Mujer` - Female
 */
export enum GenderEnum {
  Hombre = "Hombre",
  Mujer = "Mujer",
}
/**
 * * `Muy importante` - Muy Importante
 * `Importante` - Importante
 * `Poco importante` - Poco Importante
 * `Nada importante` - Nada Importante
 */
export enum FreedomEnum {
  Muy_importante = "Muy importante",
  Importante = "Importante",
  Poco_importante = "Poco importante",
  Nada_importante = "Nada importante",
}
/**
 * * `Muy importante` - Muy Importante
 * `Importante` - Importante
 * `Poco importante` - Poco Importante
 * `Nada importante` - Nada Importante
 */
export enum ForeignInvestmentEnum {
  Muy_importante = "Muy importante",
  Importante = "Importante",
  Poco_importante = "Poco importante",
  Nada_importante = "Nada importante",
}
export interface PatchedForm {
  readonly id?: number;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  age?: number;
  gender?: GenderEnum;
  country_salary?: CountrySalaryEnum;
  job_security?: JobSecurityEnum;
  unemployment_rate?: UnemploymentRateEnum;
  corruption?: CorruptionEnum;
  healthcare_importance?: HealthcareImportanceEnum;
  economy?: EconomyEnum;
  freedom?: FreedomEnum;
  air_pollution?: AirPollutionEnum;
  low_inflation?: LowInflationEnum;
  foreign_investment?: ForeignInvestmentEnum;
  city_growth?: CityGrowthEnum;
  living_area?: LivingAreaEnum;
  readonly created_at?: string;
  readonly updated_at?: string;
  user?: number;
}

export interface EmailTokenObtain {
  email: string;
  password: string;
}

/**
 * * `Muy importante` - Muy Importante
 * `Importante` - Importante
 * `Poco importante` - Poco Importante
 * `Nada importante` - Nada Importante
 */
export enum EconomyEnum {
  Muy_importante = "Muy importante",
  Importante = "Importante",
  Poco_importante = "Poco importante",
  Nada_importante = "Nada importante",
}
/**
 * * `Muy importante` - Muy Importante
 * `Importante` - Importante
 * `Poco importante` - Poco Importante
 * `Nada importante` - Nada Importante
 */
export enum CountrySalaryEnum {
  Muy_importante = "Muy importante",
  Importante = "Importante",
  Poco_importante = "Poco importante",
  Nada_importante = "Nada importante",
}
/**
 * * `Muy importante` - Muy Importante
 * `Importante` - Importante
 * `Poco importante` - Poco Importante
 * `Nada importante` - Nada Importante
 */
export enum CorruptionEnum {
  Muy_importante = "Muy importante",
  Importante = "Importante",
  Poco_importante = "Poco importante",
  Nada_importante = "Nada importante",
}
/**
 * * `Muy importante` - Muy Importante
 * `Importante` - Importante
 * `Poco importante` - Poco Importante
 * `Nada importante` - Nada Importante
 */
export enum CityGrowthEnum {
  Muy_importante = "Muy importante",
  Importante = "Importante",
  Poco_importante = "Poco importante",
  Nada_importante = "Nada importante",
}
/**
 * * `Muy importante` - Muy Importante
 * `Importante` - Importante
 * `Poco importante` - Poco Importante
 * `Nada importante` - Nada Importante
 */
export enum AirPollutionEnum {
  Muy_importante = "Muy importante",
  Importante = "Importante",
  Poco_importante = "Poco importante",
  Nada_importante = "Nada importante",
}
export interface Form {
  readonly id: number;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  age: number;
  gender?: GenderEnum;
  country_salary?: CountrySalaryEnum;
  job_security?: JobSecurityEnum;
  unemployment_rate?: UnemploymentRateEnum;
  corruption?: CorruptionEnum;
  healthcare_importance?: HealthcareImportanceEnum;
  economy?: EconomyEnum;
  freedom?: FreedomEnum;
  air_pollution?: AirPollutionEnum;
  low_inflation?: LowInflationEnum;
  foreign_investment?: ForeignInvestmentEnum;
  city_growth?: CityGrowthEnum;
  living_area?: LivingAreaEnum;
  readonly created_at: string;
  readonly updated_at: string;
  user: number;
}
